<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishReadyToRun>true</PublishReadyToRun>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <AssemblyName>FileOrganizer</AssemblyName>
    <RootNamespace>FileOrganizer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\app.ico" />
    <EmbeddedResource Include="Assets\app.png" />
  </ItemGroup>

</Project>

